version: '3'
services:
  worker:
    image: eh-app
    container_name: eh
    env_file:
      - .env.eh.prod
    entrypoint: ["/bin/bash", "-c", "chmod +x /app/start.sh && /app/start.sh && while true; do sleep 1; done"]
    restart: always
